### ISSUE TITLE
Publisher taxonomy

### ISSUE THREAD

**Issue by jazzsequence** [jazzsequence/book-review-library#1]
http://wordpress.org/support/topic/publishers-name
http://wordpress.org/support/topic/more-taxonomys

**Comment by jazzsequence** [comment]
added and will be in the next update

**Comment by crabnky** [comment]
What happened to the publisher taxonomy? I don't see it in the latest version (1.4.19)...

**Comment by jazzsequence** [comment]
@crabnky Publisher is currently available in the `develop` branch.
