### ISSUE TITLE
Pagination in Shortcode?

### ISSUE THREAD

**Issue by michelliebel** [jazzsequence/book-review-library#59]
Hi! Is there a way to add pagination to the short code so only X amount display as in Count but you can see the next 8 by pressing Next / Prev, etc.?

Thanks!
Michelle

**Comment by jazzsequence** [comment]
Not in the shortcode, but that functionality is built into the book review post type archive pages.

**Comment by michelliebel** [comment]
So if I'm using the shortcode to render the books, there isn't a way to incorporate the pagination?

**Comment by jazzsequence** [comment]
Not without custom code, although it's possible there might be a plugin that can work with it. I've used WP PageNavi but I don't think there's a way to use that without editing the code itself. https://wordpress.org/plugins/wp-pagenavi/
